### ISSUE TITLE
RequestTimout is creating a message in the SentMessages property

### ISSUE THREAD

**Issue by dikoga** [Particular/NServiceBus.Testing#127] opened 2018-07-20 17:47 UTC
Hi guys,

If you create a Saga that requests a timeout, this timeout is being added to the _messageContext.TimeoutMessages correctly and also in the _messageContext.SentMessages, but in this case I don't believe it should. Am I right? or I am missing something here?

RequestTimeout

        public async Task Handle(AnyMessage message, IMessageHandlerContext context)
        {
            await RequestTimeout<AnyMessageTimeout>(context, TimeSpan.FromMinutes(_timeToWaitForCompletionInMinutes))
                .ConfigureAwait(false);
        }

MessageContext Assert: 

        [Test]
        public async Task Timeout()
        {
            //Act
            await saga.Handle(anyMessage, _messageContext)
                .ConfigureAwait(false);
            //Assert
            Assert.AreEqual(1, _messageContext.TimeoutMessages.Length);
            Assert.AreEqual(0, _messageContext.SentMessages.Length); //This fails because there is a timeout here
        }

**Comment by adamralph** [comment] 2018-07-23 08:02
@dikoga thanks for raising this.

This is working as designed. Timeout messages are still sent messages. The difference is in the _delivery_, not the sending. I.e., they are guaranteed not to be delivered before a specfied amount of time has elapsed. If you'd like to discuss this more, I suggest raising a topic in our [Discussion Forum](https://discuss.particular.net/).

**Comment by dikoga** [comment] 2018-07-24 03:06
I would agree if this messagearrive at the time you scheduled them. If It is being delayed, it doesn’t make sense to get it right away.

**Comment by adamralph** [comment] 2018-07-24 08:18
@dikoga bear in mind that the property is named `SentMessages`. If, within a handler, delayed messages were _sent_, it is logically correct that they should appear in a `SentMessages` collection. Remember that _delivery_ is asychronous with respect to the context of the handler that sent them. It is the _delivery_ that is delayed, not the sending.

**Comment by DavidBoike** [comment] 2018-07-31 16:04
Hi @dikoga,

Adam's response above is definitely spot-on as far as the situation currently stands, but this is an area where we'd like to improve. The problem is that changing what exists in the SentMessages collection when a timeout is requested is a breaking change that would require a new major version. While we could release an 8.0.0 of the testing framework independently of NServiceBus, it's kind of nice to have those major versions aligned. Or at least, we would need a bigger reason to break that alignment since this issue has an easy (if not immediately obvious) workaround.

So for now I'm going to reopen this issue and assign it to the 8.0.0 milestone so that we'll find it when we start having conversations about a new major version of NServiceBus. I just don't want to give you any false hope that by reopening it we'll be addressing it in the immediate future.

**Comment by dvdstelt** [comment] 2021-03-17 07:59
We look at this issue again and decided to close it.

- We understand the confusion, but as Adam said, the messages are actually sent, it's the delivery that is delayed.
- The impact of changing it is far bigger than the impact of not changing anything.
  - You are still able to test and differentiate between timeout and test messages.
  - The change would result in quite a few customers having failing tests, without any clue as to why they are failing.
  - An extension method `MessagesWithoutTimeouts()` could be added that filters out the timeout messages so they don't get counted towards the business type messages being sent.

**Closed by dvdstelt** 2021-03-17 07:59 UTC
Labels: Breaking Change
