### ISSUE TITLE
Test.Initialize fails to start after upgrading to NServiceBus.Testing 5.0.5

### ISSUE THREAD

**Issue by Tonven** [Particular/NServiceBus.Testing#24] opened 2015-10-08 11:30 UTC
Test.Initialize fails to run. It throws a KeyNotFoundException. 
This was fixed in 5.0.4 #20.
Now it happens again. But now adding Assembly.LoadFrom("NServiceBus.Testing.dll") doesn't help.
```
            var assemblies = new List<Assembly>
            {
                typeof(IMessage).Assembly,
                typeof(SchemaImportedInFag).Assembly,
                typeof(AutorisasjonOgLisensFormReceivedEvent).Assembly,
                Assembly.LoadFrom("NServiceBus.Testing.dll")
            };

            Test.Initialize(x =>
                x.AssembliesToScan(assemblies));

**Comment by andreasohlund** [comment] 2015-10-21 12:09
Duplicate of #20

**Closed by andreasohlund** 2015-10-21 12:09 UTC
